### ISSUE TITLE
Use crypto.subtle.generateKey for generating keys

### ISSUE THREAD

**Issue by ItalyPaleAle** [rohanharikr/keychat.online#2]
In this line: https://github.com/rohanharikr/chatsecure.online/blob/fc52f7a4a2662c8bb7832609f492320ae0fe0cc0/client/src/utils/secretKeyGenerator.js#L3

The Math.random function shouldn't be trusted to generate strong random numbers for crypto purposes. Consider using https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey instead

**Comment by rohanharikr** [comment]
@ItalyPaleAle This is only to generate the secretcode that allows

**Comment by rohanharikr** [comment]
@ItalyPaleAle Thanks for opening the issue. However, the secretKeyGenerator exists only to generate a session code (the 5 digit code used to share)

The keypairs (used for enc and dec of the actual messages) are generated using the TweetNaCl library.
```
const keys = nacl.box.keyPair(); \\ {publicKey: Unit8Array(32)[...], secretKey:Unit8Array(32)[...]}
```

**Comment by ItalyPaleAle** [comment]
Thanks for explaining :)
